/**
 * Client-side table sorting, delivered as an anywidget module. The plugin
 * bundle has node-only imports the browser can't load, so the widget source is
 * embedded here as a string and written next to the bundle at build time.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const SORT_WIDGET_SOURCE = `// Generated by myst-listing (src/sort-widget.ts); do not edit.
export default {
  render({ model }) {
    const columns = model.get("columns");
    const orders = model.get("orders"); // "column:dir" -> sorted row order, computed at build (plugin.ts)
    const firstDirection = model.get("firstDirection") || []; // first-click direction per column: text 1 (A-Z), numbers/dates -1
    const root = document.querySelector(".myst-listing-sort-" + model.get("id"));
    // Header cells live in the light DOM and survive effect re-runs; wire once.
    if (!root || root.dataset.mystSortWired) return;
    root.dataset.mystSortWired = "1";

    // Data rows in build order: the entries in orders point into this list.
    const rows = Array.from(root.querySelectorAll("tr.myst-listing-item"));

    // The hover/focus arrow reveal needs a stylesheet (inline styles can't
    // express :hover), added once per page.
    if (!document.querySelector("style[data-myst-listing-sort]")) {
      const style = document.createElement("style");
      style.dataset.mystListingSort = "1";
      style.textContent = [
        // Arrows visible at rest so readers can tell the table is sortable.
        ".myst-sort-arrow{display:inline-block;width:1em;margin-left:0.2em;opacity:0.35;transition:opacity 0.15s;}",
        "th:hover>.myst-sort-arrow,th:focus-visible>.myst-sort-arrow{opacity:0.7;}",
        "th[aria-sort]>.myst-sort-arrow{opacity:1;}",
        // Grey-with-alpha tint reads on light and dark themes; :has scopes it
        // to sortable headers so other tables on the page are untouched.
        "th:has(>.myst-sort-arrow):hover{background:rgba(128,128,128,0.12);}",
      ].join("");
      document.head.append(style);
    }

    const ths = Array.from(root.querySelectorAll("th"));
    let current = null;
    let dir = 1;
    ths.forEach((th, i) => {
      const col = columns[i];
      const arrow = document.createElement("span");
      arrow.className = "myst-sort-arrow";
      arrow.textContent = "⇅";
      th.appendChild(arrow);
      th.style.cursor = "pointer";
      // Keyboard-focusable, keeping the implicit columnheader role: aria-sort
      // is only announced on column headers.
      th.tabIndex = 0;
      const activate = () => {
        dir = current === col ? -dir : firstDirection[i] || 1;
        current = col;
        ths.forEach((h) => h.removeAttribute("aria-sort"));
        th.setAttribute("aria-sort", dir === 1 ? "ascending" : "descending");
        root.querySelectorAll(".myst-sort-arrow").forEach((s) => (s.textContent = "⇅"));
        arrow.textContent = dir === 1 ? "↑" : "↓";
        // appendChild moves existing nodes, so this reorders in place.
        (orders[col + ":" + dir] || []).forEach((r) => rows[r] && rows[r].parentNode.appendChild(rows[r]));
      };
      th.addEventListener("click", activate);
      th.addEventListener("keydown", (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          activate();
        }
      });
    });
  },
};
`;

const SORT_WIDGET_FILE = join(dirname(fileURLToPath(import.meta.url)), "myst-listing-sort.mjs");

/** Write the widget module and return its page-relative path for the anywidget
 * `esm` field. Skip the write when the file already matches: MyST hashes
 * assets by mtime, so a rewrite would duplicate the asset on every build.
 * URL-loaded plugins work too: mystmd caches them inside the project's _build. */
export function sortWidgetEsm(vfile: any): string {
  if (!existsSync(SORT_WIDGET_FILE) || readFileSync(SORT_WIDGET_FILE, "utf-8") !== SORT_WIDGET_SOURCE) {
    writeFileSync(SORT_WIDGET_FILE, SORT_WIDGET_SOURCE);
  }
  // Forward slashes even on Windows: this is a URL path, not a file path.
  return relative(dirname(vfile.path), SORT_WIDGET_FILE).split("\\").join("/");
}
