name: Release

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    permissions:
      contents: write
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build plugin
        run: bun run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag: ${{ github.ref }}
          files: |
            dist/plugin.mjs
